name: Railchess
version: '${project.version}'
main: me.momochai.railchess.Railchess
api-version: '1.20'
load: POSTWORLD
commands:
  rcstand:
    permission: railchess.play
  rcedit:
    permission: railchess.edit
  rcgame:
    permission: railchess.subscribe
  rcmap:
    permission: railchess.edit
  rcreplay:
    permission: railchess.subscribe
  rclog:
    permission: railchess.subscribe
  rcfix:
    permission: railchess.op
permissions:
  railchess.op:
    description: Permission for ops
    default: op
    children:
      railchess.edit: true
      railchess.play: true
      railchess.subscribe: true
  railchess.edit:
    description: Permission for editing maps
    default: op
    children:
      railchess.play: true
      railchess.subscribe: true
  railchess.play:
    description: Permission for playing Railchess games
    default: true
    children:
      railchess.subscribe: true
  railchess.subscribe:
    description: Permission for subscribing to (i.e., spectating) Railchess games